version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "npm dependencies"
      - "need review"
    reviewers:
      - "wangxue0314"
    assignees:
      - "wangxue0314"
    commit-message:
      prefix: "npm"
